apiVersion: v1
kind: Service
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: cluster-1    
  labels:
    app: anthos-demo
  name: anthos-demo
  namespace: demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: anthos-demo
  sessionAffinity: None
  type: ClusterIP
